### PR TITLE
Feature/styling updates

### PR DESCRIPTION
**Pull request by dietza**
## *Purpose:*
*What does this merge do? Check all that apply.*
- [ ] Adds a new feature
- [x] Improves an existing feature
- [ ] Fixes a bug
- [ ] Cleans up (logs, tests, etc.)

Adds new fonts and icons,
Updates to use more sematic tags in JSX,
Achieves 100% on LightHouse accessibility audit

## Checklist:
- [x] I have performed a self-review of my own code
- [ ] I have used tests to prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my change

### CODE REVIEW

**Comment by dietza** [comment]
9C583138-F1E0-476D-A27F-6F8C44625496_1_105_c

**Review by christina-cook — APPROVED** [review]
I like the style changes! Good work Allison!

**Comment by colefiscus** [comment]
I really like what you've done with it too! The  only thing I'm curious about is if black text would show better than the white against that kind of faded white overlay. But if it passes Lighthouse and it looks better the white is fine with me too!

**Comment by dietza** [comment]
> I really like what you've done with it too! The only thing I'm curious about is if black text would show better than the white against that kind of faded white overlay. But if it passes Lighthouse and it looks better the white is fine with me too!

Agreed, that could probably be more readable. Lighthouse didn't have an issue with that, but it may just be a gap in testing as that contrast issue is exactly the reason our buttons now have a darker background color behind the white text.

**Pull request merged**
